[server]
app_name="nanonime"
mode = "info"
port = "8080"
http_timeout = 60
cache_expired = 24
cache_purged = 60
api_version = "1"

[anime_api]
base_url = "http://localhost:3001"
timeout = 30

[manga_api]
base_url = "http://localhost:3002"
timeout = 30

[database]
db_driver = "mysql"
db_host = "localhost"
db_port = "3306"
db_name = "go_modular"
db_username = "root"
db_password = "ahmadrafi01"

[pool]
conn_idle = 200
conn_max = 300
conn_lifetime = 60

[jwt]
day_expired = 60
signature_key = "4WSRLWxJdm"

[manga]
base_url = "http://localhost:3002"
timeout = 30
