name: Build & Release Android APK

on:
    push:
        branches:
            - test

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Flutter
              uses: subosito/flutter-action@v2
              with:
                  flutter-version: "3.38.5"

            - name: Generate .env from GitHub Actions env
              run: |
                  echo "API_URL=${{ secrets.API_URL }}" > .env
                  echo "API_VERSION=${{ secrets.API_VERSION }}" >> .env

            - name: Install dependencies
              run: flutter pub get

            - name: Build APK
              run: flutter build apk --release

            - name: Get version name
              id: version
              run: |
                  VERSION_NAME=$(grep 'version:' pubspec.yaml | awk '{print $2}' | cut -d"+" -f1)
                  echo "version_name=$VERSION_NAME" >> $GITHUB_OUTPUT

            - name: Create Release
              id: create_release
              uses: softprops/action-gh-release@v2
              with:
                  tag_name: v${{ steps.version.outputs.version_name }}-${{ github.sha }}
                  name: "Release v${{ steps.version.outputs.version_name }}-${{ github.sha }}"
                  draft: true
                  prerelease: true
                  generate_release_notes: true
              env:
                  GITHUB_TOKEN: ${{ secrets.GT_TOKEN }}

            - name: Upload APK to Release
              uses: softprops/action-gh-release@v2
              with:
                  tag_name: v${{ steps.version.outputs.version_name }}-${{ github.sha }}
                  files: build/app/outputs/flutter-apk/app-release.apk
              env:
                  GITHUB_TOKEN: ${{ secrets.GT_TOKEN }}
